import type { Metadata } from "next";
import "./globals.css";
import ThemeRegistry from './ThemeRegistry';

export const metadata: Metadata = {
  title: "ORCA Schema Merger | Schema Splitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
